### ISSUE TITLE
5.2-using-convnets-with-small-datasets

### ISSUE THREAD

**Issue by mwddevcenter** [fchollet/deep-learning-with-python-notebooks#88]
ImportError: Could not import PIL.Image. The use of `array_to_img` requires PIL.
Assume the train_dir path is not correct. How can i fix it?

**Comment by mwddevcenter** [comment]
I fixed it by install pillow lib, Thanks all.
pip install pillow

**Comment by morenoh149** [comment]
@mwddevcenter please close

**Comment by AJFeng** [comment]
> I fixed it by install pillow lib, Thanks all.
> pip install pillow

I don't think it is the problem of his.
I have the pillow pakege but still have this problem.
I don't remember what I did for this problem. But now I don't have this error and came out to another error. Now sure if the new error was affected by this error.

**Comment by codekiln** [comment]
Suggestion: instead of using `from keras.preprocessing import image`, use: 

```python
import tensorflow as tf

load_img = tf.keras.utils.load_img
img_to_array = tf.keras.utils.img_to_array
array_to_img = tf.keras.utils.array_to_img
```

**Comment by ifond** [comment]
YES!!! I have received your E-mail——Steven Lee
